#!/usr/bin/env bash
set -euo pipefail

jq -e '.terminal' "$THEME_JSON" >/dev/null 2>&1 || exit 0

TERMINAL_CONFIG="$HOME/.config/terminal/colors.conf"
mkdir -p "$(dirname "$TERMINAL_CONFIG")"

BACKGROUND=$(jq -r '.terminal.background // empty' "$THEME_JSON")
FOREGROUND=$(jq -r '.terminal.foreground // empty' "$THEME_JSON")

{
    echo "# Generated by theme-manager. Do not edit this file manually."
    [ -n "$BACKGROUND"] && echo "background=$BACKGROUND"
    [ -n "$FOREGROUND"] && echo "foreground=$FOREGROUND"
} > "$TERMINAL_CONFIG"